image: bitbucketpipelines/scala-sbt:scala-2.12

pipelines:
  branches:
    master:
      - step :
          script: # Modify the commands below to build your repository.
            - mkdir ~/.bintray
            - printf "realm = Bintray API Realm\nhost = upstartcomme rce.bintray.com\nuser = $BINTRAY_USER\npassword = $BINTRAY_PASS\n\nrealm = Bintray\nhost = upstartcommerce.bintray.com\nuser = $BINTRAY_USER\npassword = $BINTRAY_PASS\n">>~/.bintray/.credentials
            - sbt compile test
